language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - extra-android-m2repository
  - ${ANDROID_TARGET}
  - sys-img-${ANDROID_ABI}-google_apis-23
script:
  - android list targets
  # - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -k "system-images;${ANDROID_TARGET};google_apis;${ANDROID_ABI}"
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
