language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - $ANDROID_TARGET
  - sys-img-${ANDROID_ABI}-google_apis-25
before_install:
  # https://github.com/travis-ci/travis-ci/issues/8874#issuecomment-350350607
  - yes | sdkmanager "platforms;android-27"
  # https://stackoverflow.com/questions/42554337/cannot-launch-avd-in-emulatorqt-library-not-found
  - yes | sdkmanager "emulator"
  - avdmanager list target
  - echo no | avdmanager create avd --force -n test -k "system-images;${ANDROID_TARGET};google_apis;${ANDROID_ABI}"
  - which emulator
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
