language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-27
    - ANDROID_ABI=x86
android:
  components:
  - tools
  - platform-tools
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
  # https://github.com/travis-ci/travis-ci/issues/8874#issuecomment-350350607
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "system-images;${ANDROID_TARGET};google_apis_playstore;${ANDROID_ABI}"
  # https://stackoverflow.com/questions/42554337/cannot-launch-avd-in-emulatorqt-library-not-found
  - yes | sdkmanager "emulator"
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | avdmanager create avd --force -n test -k "system-images;${ANDROID_TARGET};google_apis_playstore;${ANDROID_ABI}"
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
