version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-23-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample-app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: sdkmanager
          command: sdkmanager "build-tools;23.0.3"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          environment:
            TERM: dumb
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample-app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: sample-app/build/reports
          destination: reports
      - store_test_results:
          path: sample-app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
